name: Code Quality

on:
  push:
    branches: [ "3.0", "main", "master" ]
  pull_request:
    branches: [ "3.0", "main", "master" ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: PHP_CodeSniffer
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: cs2pr, phpcs
        
    - name: Run PHPCS
      run: phpcs --report=checkstyle --standard=phpcs.xml.dist src/ | cs2pr
      continue-on-error: true

  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: memcached, mbstring, xml, ctype, json
        tools: phpstan
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs --no-dev
      
    - name: Run PHPStan
      run: phpstan analyse --configuration=phpstan.neon.dist --error-format=github
      continue-on-error: true

  psalm:
    runs-on: ubuntu-latest
    name: Psalm
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: memcached, mbstring, xml, ctype, json
        tools: psalm
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs --no-dev
      
    - name: Run Psalm
      run: psalm --config=psalm.xml.dist --output-format=github
      continue-on-error: true